### ISSUE TITLE
zlib.crc32(url) may generate the same file name with different urls.

### ISSUE THREAD

**Issue by mazm13** [igorbrigadir/DownloadConceptualCaptions#5]
https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/b76830320ef2a3dc8fee08615c820cf28bf9481c/download_data.py#L47-48

here is an example:
"http://c8.alamy.com/comp/KCBYE7/horizontal-panel-with-a-row-of-flowers-above-a-frieze-with-figures-KCBYE7.jpg" and "http://l7.alamy.com/zooms/39d784cf80c24f3aaec12f6f95bac960/working-the-fields-near-hue-vietnam-pic-rob-judges-aaxm30.jpg" are two different image urls. But the function _file_name() generates the same name which is "training/278647033".

**Comment by igorbrigadir** [comment]
Aw, that's annoying - probably should have checked that when i put that file name function in. I just checked again, this also happens in the validation set with:

"https://i2.wp.com/static1.businessinsider.com/image/518964116bb3f7dc7e000018-1200/tostitos--the-not-so-hidden-design-within-this-logo-conjures-up-feelings-of-togetherness-and-friendship-over-chips-and-salsa.jpg" and "https://www.ocregister.com/wp-content/uploads/migration/nf0/nf0p11-b88256606z.120141113230307000g8r69gtk.10.jpg?w=620"

Since the actual file names don't matter, ~~and these are the only 2 cases in the dataset, i think i'll just hardcode a +1 to those cases. That way you don't have to rename lots of files and can just restart where you left off.~~ 

I added the row id to the name too, and that makes it unique - it means you can't resume right away, but this fixes a lot of bad file name collisions. https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/master/download_data.py#L48

Thanks for finding this!
